// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// DeleteExpenseParams is parameters of DeleteExpense operation.
type DeleteExpenseParams struct {
	// Expense id to delete.
	ExpenseID int
}

func unpackDeleteExpenseParams(packed middleware.Parameters) (params DeleteExpenseParams) {
	{
		key := middleware.ParameterKey{
			Name: "expenseID",
			In:   "query",
		}
		params.ExpenseID = packed[key].(int)
	}
	return params
}

func decodeDeleteExpenseParams(args [0]string, argsEscaped bool, r *http.Request) (params DeleteExpenseParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: expenseID.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "expenseID",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.ExpenseID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "expenseID",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
