// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// DeleteExpense implements DeleteExpense operation.
	//
	// Deletes an expense.
	//
	// DELETE /api/expenses/{userId}
	DeleteExpense(ctx context.Context, params DeleteExpenseParams) error
	// GetAllExpenses implements GetAllExpenses operation.
	//
	// Returns all expenses.
	//
	// GET /api/expenses/{userId}
	GetAllExpenses(ctx context.Context, params GetAllExpensesParams) (GetAllExpensesRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
