// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// DeleteExpense implements DeleteExpense operation.
//
// Deletes an expense.
//
// DELETE /api/expenses/{userId}
func (UnimplementedHandler) DeleteExpense(ctx context.Context, params DeleteExpenseParams) error {
	return ht.ErrNotImplemented
}

// GetAllExpenses implements GetAllExpenses operation.
//
// Returns all expenses.
//
// GET /api/expenses/{userId}
func (UnimplementedHandler) GetAllExpenses(ctx context.Context, params GetAllExpensesParams) (r GetAllExpensesRes, _ error) {
	return r, ht.ErrNotImplemented
}
